
FROM node:16-alpine
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
RUN yarn
# Copy app files
COPY . .
# Expose port
EXPOSE 3000
# Start the app
CMD [ "yarn", "start" ]