name: CI
on: 
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Change Directory
      run: cd kimchechallenge
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx